## 데이터 전처리
1. 데이터 클린징
2. 결손값 처리
3. 데이터 인코딩
4. 데이터 스케일링
5. 이상치 제거 
6. feature 선택, 추출 및 가공 

one-hot은 column으로 만든 후 해당 컬럼만 1을 표시한다.  
(label은 수가 높다고 우선순위도 높다는 평가를 할 수 있어서)  
  
label은 각 label마다 숫자를 넣는 것  



In [1]:
items = ['냉장고', '에어컨', ' TV', '컴퓨터', '에어컨', ' TV', '컴퓨터']
items

['냉장고', '에어컨', ' TV', '컴퓨터', '에어컨', ' TV', '컴퓨터']

In [2]:
from sklearn.preprocessing import LabelEncoder

#범주형 preprocessing

## label encoding

In [3]:
encoder=LabelEncoder()

encoder

LabelEncoder()

In [6]:
encoder.fit(items)
result = encoder.transform(items)

# 학습시키기 
# 실제 학습을 기준으로 transform을 시킴

In [7]:
result

array([1, 2, 0, 3, 2, 0, 3])

In [8]:
encoder.classes_ 

array([' TV', '냉장고', '에어컨', '컴퓨터'], dtype='<U3')

In [9]:
print('디코딩 원본 값:',encoder.inverse_transform([2, 0, 1, 1, 3, 3]))

#  숫자를 역으로 

디코딩 원본 값: ['에어컨' ' TV' '냉장고' '냉장고' '컴퓨터' '컴퓨터']


In [24]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

### one-hot encoding

In [11]:
ohe=OneHotEncoder()

In [13]:
# 세로로 convert
label=result.reshape(-1,1)

# result의 요소를 column이 1개인 것으로 만들었음 

In [14]:
ohe.fit(label)

OneHotEncoder()

In [15]:
result_ohe=ohe.transform(label)

In [16]:
result_ohe

# 메모리를 아끼기 위해서 요약본만 보여줌 

<7x4 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [19]:
result_ohe.toarray()

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [20]:
dict_items={"items": ['냉장고', '에어컨', ' TV', '컴퓨터', '에어컨', ' TV', '컴퓨터']}

In [26]:
df= pd.DataFrame(dict_items)

df

items
0   냉장고
1   에어컨
2    TV
3   컴퓨터
4   에어컨
5    TV
6   컴퓨터

In [29]:
pd.get_dummies(df["items"])

TV  냉장고  에어컨  컴퓨터
0    0    1    0    0
1    0    0    1    0
2    1    0    0    0
3    0    0    0    1
4    0    0    1    0
5    1    0    0    0
6    0    0    0    1

### feature scaling

균질화된 데이터로 분석하는 것이 좋음.  
  
scaling방법이 있음 - preprocessing부분에 있음  
  
통계기준 => 표준화 (자연계 수치)  
통계 구간에 있는 애들이 수렴하게    
  
측정된 것 => 정규화 
  
  


#### standard scaler

In [31]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())


feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [32]:
from sklearn.preprocessing import StandardScaler


In [33]:
s_scaler=StandardScaler()

In [35]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [34]:
s_scaler.fit(iris_df)

# 자동 전환

StandardScaler()

In [36]:
s_scaler.transform(iris_df)

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [39]:
s_result=s_scaler.transform(iris_df)

df= pd.DataFrame(s_result, columns=iris_df.columns)

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [41]:
df["sepal length (cm)"].mean()

-1.6903145549918008e-15

In [42]:
df.describe()

# 평균은 0에 가깝고 표준편차는 1에 가깝다.

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -1.409243e-15  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

#### minmax scaler

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
m_scaler=MinMaxScaler()

In [45]:
m_scaler.fit(iris_df)

MinMaxScaler()

In [50]:
m_scaler.transform(iris_df)

# 0에서 1 사이로 

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [51]:
m_result = m_scaler.transform(iris_df)

In [52]:
df=pd.DataFrame(m_result, columns=iris_df.columns)

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [53]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

## Collect Dataset

train data밖에 없음   
검증을 위해 test data가 필요함  
  
model_selection의 train_test_split을 사용한다.  
비율만 정해두면 된다.  
  
2세트 4개가 나온다.
train, test가 나오는데 test_size만큼 test에게 준다.

data에서 train, test  (x)  
target에서 train, test  (y)  
  
  
validation이 중요함.  
  
train의 data가 쏠릴 수 있다 -> 해결법 : n-fold cross validation  
  
    다 나눠서 공부를 한 다음에 평균을 내기

### K-fold  


In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
kfold = KFold(n_splits=5)
# 몇 등분을 할 것인지 

cv_accuracy = []
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [55]:
kfold.split(iris.data)


<generator object _BaseKFold.split at 0x0000018ECBC1EC80>

In [56]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [57]:
list(kfold.split(iris.data))

# 5등분중에 4개를 학습하고 남은 하나 

[(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
          69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
          82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
          95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
         121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
         134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
         147, 148, 149]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27, 

In [58]:
n_iter=0

for idx_train, index_test in kfold.split(iris.data):
    print(idx_train, index_test)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [70]:
n_iter=0
cv_acc=0

for idx_train, idx_test in kfold.split(iris.data):
    X_train, X_test= iris.data[idx_train], iris.data[idx_test]
    y_train, y_test= iris.target[idx_train], iris.data[idx_test]
    
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    n_iter+=1
    size_train=X_train.shape[0]
    size_test=X_test.shape[1]
    
    accuracy= accuracy_score(y_test, pred)
    cv_acc+=accuracy
    

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

### cross_val_score

In [71]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score , cross_validate
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target


In [75]:
cross_val_score(dt_clf, data, label, cv=5, scoring='accuracy')

# 어던 것을 돌릴 것인지, feature와 label이 뭔지, cv옵션으로 몇 번 돌릴 것인지

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])