# Numpy

In [1]:
import numpy as np

In [2]:
A=[[1,0],[0,1]]
B=[[0,1],[1,0]]

A+B 

# list는 더하는 것이 append의 개념이다

[[1, 0], [0, 1], [0, 1], [1, 0]]

In [4]:
A=np.array([[1,0],[0,1]])
B=np.array([[0,1],[1,0]])

A+B 
#np.array로 해야 값이 더해진다.

array([[1, 1],
       [1, 1]])

### vector

In [5]:
A=np.array([1,2,3])
B=np.array([4,5,6])

print("A==",A,", B==",B)
print("vector A shape=",A.shape,", vector B shape=",B.shape)
print("vector A dimension=",A.ndim,", vector B dimension=",B.ndim) #numpy dimension

A== [1 2 3] , B== [4 5 6]
vector A shape= (3,) , vector B shape= (3,)
vector A dimension= 1 , vector B dimension= 1


### matrix

In [6]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[-1,-2,-3],[-4,-5,-6]])

print("matrix A =",A)
print("matrix B =",B)
print("matrix A shape==",A.shape,", matrix B shape==",B.shape)
print("matrix A dimension==",A.ndim,", matrix B dimension==",B.ndim)

matrix A = [[1 2 3]
 [4 5 6]]
matrix B = [[-1 -2 -3]
 [-4 -5 -6]]
matrix A shape== (2, 3) , matrix B shape== (2, 3)
matrix A dimension== 2 , matrix B dimension== 2


### 산술 연산

In [8]:
A=np.array([1,2,3])
B=np.array([4,5,6])

print("A==",A,", B==",B)
print("A+B==",A+B)
print("A-B==",A-B)
print("A*B==",A*B)
print("A/B==",A/B)

# 무조건 원소의 개수가 같아야 한다.

A== [1 2 3] , B== [4 5 6]
A+B== [5 7 9]
A-B== [-3 -3 -3]
A*B== [ 4 10 18]
A/B== [0.25 0.4  0.5 ]


### 형 변환

In [11]:
C=np.array([1,2,3])
print("C.shape==",C.shape)
print(C);
C=C.reshape(1,3)
print("C.shape==",C.shape)

print(C)

C.shape== (3,)
[1 2 3]
C.shape== (1, 3)
[[1 2 3]]


In [12]:
D=np.array([[1,2,3],[4,5,6]])

print("D.shape==",D.shape)
print(D)

D=D.reshape(3,2)
print("D.shape==",D.shape)
print(D)

D.shape== (2, 3)
[[1 2 3]
 [4 5 6]]
D.shape== (3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [13]:
A=np.array([
    [1,2,3,4],
    [10,20,30,40],
    [100,200,300,400]
])

print(A.shape)

(3, 4)


In [14]:
B=A.reshape(-1,3)

print(B)
print(B.shape)

[[  1   2   3]
 [  4  10  20]
 [ 30  40 100]
 [200 300 400]]
(4, 3)


In [15]:
C=A.reshape(-1,6)
print(C)
print(C.shape)

[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]
(2, 6)


### broadcast

In [16]:
A=np.array([[1,2],[3,4]])
B=5

print(A+B)

[[6 7]
 [8 9]]


In [17]:
C=np.array([[1,2],[3,4]])
D=np.array([4,5])

print(C+D)

[[5 7]
 [7 9]]


### Transpose 전치 행렬

In [18]:
A=np.array([[1,2],[3,4],[5,6]])

B=A.T

print("A.shape=",A.shape,", B.shape=",B.shape)

print("A=",A)
print("B=",B)

A.shape= (3, 2) , B.shape= (2, 3)
A= [[1 2]
 [3 4]
 [5 6]]
B= [[1 3 5]
 [2 4 6]]


In [19]:
C=np.array([1,2,3,4,5])

D=C.T

print("C=",C)
print("D=",D)

print("C.shape=",C.shape,", D.shape=",D.shape)

#1차원은 열과 행을 구별하지 않기에 전치행렬을 해도 바뀌지 않는다.

C= [1 2 3 4 5]
D= [1 2 3 4 5]
C.shape= (5,) , D.shape= (5,)


In [21]:
E=C.reshape(1,5)

F=E.T

print("E=",E)
print("F=",F)

print("E.shape=",E.shape,", F.shape=",F.shape)

E= [[1 2 3 4 5]]
F= [[1]
 [2]
 [3]
 [4]
 [5]]
E.shape= (1, 5) , F.shape= (5, 1)


### 행렬 곱

In [22]:

A=np.array([[1,2,3],[4,5,6]])
B=np.array([[-1,-2],[-3,-4],[-5,-6]])

C=np.dot(A,B)

print("A.shape=",A.shape,", B.shape=",B.shape)
print("C.shape=",C.shape)

print(C)


A.shape= (2, 3) , B.shape= (3, 2)
C.shape= (2, 2)
[[-22 -28]
 [-49 -64]]


### 행렬 원소 접근 - indexing, slicing

In [25]:
A=np.array([[10,20],[30,40],[50,60]])

print("A.shape=",A.shape)
print(A)

print("A[0,0]==",A[0,0])
print("A[2,1]==",A[2,1])
print("A[:,0]==",A[:,0])
print("A[0:-1, 1:2]==",A[0:-1,1:2])
# 0에서 1번까지
print("A[:,:]===",A[:,:])

A.shape= (3, 2)
[[10 20]
 [30 40]
 [50 60]]
A[0,0]== 10
A[2,1]== 60
A[:,0]== [10 30 50]
A[0:-1, 1:2]== [[20]
 [40]]
A[:,:]=== [[10 20]
 [30 40]
 [50 60]]


### Iterator

In [26]:
A=np.array([[10,20,30,40],[50,60,70,80]])
it=np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    idx=it.multi_index
    print("index -> ",idx,", value -> ",A[idx])
    it.iternext()

index ->  (0, 0) , value ->  10
index ->  (0, 1) , value ->  20
index ->  (0, 2) , value ->  30
index ->  (0, 3) , value ->  40
index ->  (1, 0) , value ->  50
index ->  (1, 1) , value ->  60
index ->  (1, 2) , value ->  70
index ->  (1, 3) , value ->  80


### 유용한 함수

In [27]:
number1=np.random.rand(3)
number2=np.random.rand(1,3)
number3=np.random.rand(3,1)

print("random_number 1==",number1)
print("random number 2==",number2)
print("random number 3==",number3)

# rand함수는 0과 1 사이의 임의의 실수값을 얻고 싶을 때 사용
# 인자를 추가하여 벡터나 행렬로 생성할 수 있다.

random_number 1== [0.36231146 0.06777056 0.41384234]
random number 2== [[0.26674439 0.09852064 0.06957202]]
random number 3== [[0.8340346 ]
 [0.9310289 ]
 [0.44087903]]


In [28]:
A=np.array([2,6,3,1])

print("np.max(A)==",np.max(A))
print("np.argmax(A)==",np.argmax(A))
#최댓값을 갖고 있는 벡터나 행렬의 인덱스 값을 알려주는 함수

np.max(A)== 6
np.argmax(A)== 1
